spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_lotto
    username: root
    password: mongma
    driver-class-name: com.mysql.cj.jdbc.Driver
